### ISSUE TITLE
概率出现"Max retries exceeded with url:XXXX"的错误

### ISSUE THREAD

**Issue by QRQaccount** [dataabc/weibo-follow#17]
在headers中添加上'Connection': 'close'能解决

**Comment by dataabc** [comment]
感谢建议，发现问题并给出了解决方案。能否将您修改后的代码以pull request形式提交呢？这样还可以成为本程序的Contributor，如果不方便，我会自己在明天添加这个修改。

再次感谢建议。

**Comment by QRQaccount** [comment]
> 感谢建议，发现问题并给出了解决方案。能否将您修改后的代码以pull request形式提交呢？这样还可以成为本程序的Contributor，如果不方便，我会自己在明天添加这个修改。
> 
> 再次感谢建议。

我只是自己在使用的时候做了点小修改。也没有去测试过这个修改是否能完全解决这个问题。还是你在综合考量后决定是否修改吧。

**Comment by dataabc** [comment]
好的，我考虑下，感谢
